#:schema ./.aviutl2-cli/aviutl2.schema.json
# 設定ファイルについては https://github.com/sevenc-nanashi/aviutl2-cli を参照してください。

[project]
id = "sevenc-nanashi.vintage-auf2"
name = "vintage.auf2"
version = "0.1.0"

[development]
aviutl2_version = "latest"

[artifacts.vintage-auf2]
destination = "Plugin/vintage.auf2"

[artifacts.vintage-auf2.profiles.debug]
build = "cargo build"
source = "target/debug/vintage_auf2.dll"

[artifacts.vintage-auf2.profiles.release]
build = "cargo build --release"
source = "target/release/vintage_auf2.dll"

[release]
prebuild = ["cargo about generate ./about.hbs -o ./release/package.txt"]
package_template = "./release/package.txt"
zip_name = "vintage-v{version}"
package_information = "{name} v{version} / 音声を昔のビデオっぽくするフィルタープラグイン"
